name: news
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.6
  flutter_bloc: 8.1.3
  http: 1.1.0
  cached_network_image: 3.2.3
  intl: 0.18.1
  url_launcher: 6.1.14
  shared_preferences: 2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.3

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
